add components & basic layout for landing page
chingu-voyages/v24-geckos-team-02 pull request #29
Opened 2020-10-13 10:46 UTC by snrelghgub

Our basic page layout has the following React component structure for our App /> as we agreed yesterday:

Navbar />
Header />
Search /> --> SeachBar />
Result /> --> Card />
Footer />
*where SearchBar /> is a child component of Search /> & Card /> is a child component of Result />
**please also note I decided to use the name Card /> instead of Volume /> to separate & isolate our dependency on Google Books API's naming conventions in its data model. 

Thanks in advance for reviewing my PR & providing me with your feedback.

2020-10-13 18:57 UTC, ArunJose commented
Instead of naming the component Results I would suggest to pick a more suitable name like BookCardList/BookCard, BookList/BookListItem, CardList/Card,  BookCards/BookCard etc. We can can probably reuse the same component in other places like when displaying books in favorites. Also, it will more accurately describe what the component is rendering.

2020-10-14 03:07 UTC, snrelghgub commented
that's really smart suggestion @ArunJose. I updated to CardList/Card already - I definitely agree that it is a more appropriate name combination to represent its reusability. Thanks for your constructive input 👍

2020-10-14 03:58 UTC, ArunJose requested changes
Request you to change name of exported component in Footer.tsx

2020-10-14 03:58 UTC, ArunJose commented on src/components/Footer.tsx
> +      <p>*Footer info goes here*</p>
Exported function should be named Footer

2020-10-14 04:45 UTC, ArunJose approved these changes

2020-10-14 12:29 UTC, merged